ll |grep _0.config|grep case2
ll |grep _0.config|grep case1_
ll |grep _0.config|grep case3_
ll |grep _0.config|grep case5_
ll |grep _0.config|grep case4_
ll |grep _0.config|grep case6_
ll |grep _0.config|grep case8_
ll |grep _0.config|grep case7_
ll |grep _0.config|grep case9_
ll |grep _0.config|grep case11_
ll |grep _0.config|grep case10_
ll |grep _0.config|grep case12_
